spring.config.import=optional:configserver:

server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never

postali.url=https://postali.app

postali.validacion-obligatoria=true
spring.cloud.openfeign.client.config.postaliClient.connect-timeout=3000
spring.cloud.openfeign.client.config.postaliClient.read-timeout=5000

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100

jwt.expiration-minutes=60
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server.port=${PORT:8080}
server.forward-headers-strategy=framework

# Simulaciones GestoPago y Postali
gestopago.auth.url=http://localhost:9999
gestopago.auth.id-distribuidor=0
gestopago.auth.codigo-dispositivo=dev
gestopago.auth.password=dev
gestopago.catalogo.url=http://localhost:9999
postali.url=https://postali.app
